package db

var SQLKeywords = map[string]bool{
	"all":               true,
	"analyse":           true,
	"analyze":           true,
	"and":               true,
	"any":               true,
	"array":             true,
	"as":                true,
	"asc":               true,
	"asymmetric":        true,
	"both":              true,
	"case":              true,
	"cast":              true,
	"check":             true,
	"collate":           true,
	"column":            true,
	"constraint":        true,
	"create":            true,
	"current_catalog":   true,
	"current_date":      true,
	"current_role":      true,
	"current_time":      true,
	"current_timestamp": true,
	"current_user":      true,
	"default":           true,
	"deferrable":        true,
	"desc":              true,
	"distinct":          true,
	"do":                true,
	"else":              true,
	"end":               true,
	"except":            true,
	"false":             true,
	"fetch":             true,
	"for":               true,
	"foreign":           true,
	"from":              true,
	"grant":             true,
	"group":             true,
	"having":            true,
	"in":                true,
	"initially":         true,
	"intersect":         true,
	"into":              true,
	"lateral":           true,
	"leading":           true,
	"limit":             true,
	"localtime":         true,
	"localtimestamp":    true,
	"not":               true,
	"null":              true,
	"offset":            true,
	"on":                true,
	"only":              true,
	"or":                true,
	"order":             true,
	"placing":           true,
	"primary":           true,
	"references":        true,
	"returning":         true,
	"select":            true,
	"session_user":      true,
	"some":              true,
	"symmetric":         true,
	"table":             true,
	"then":              true,
	"to":                true,
	"trailing":          true,
	"true":              true,
	"union":             true,
	"unique":            true,
	"user":              true,
	"using":             true,
	"variadic":          true,
	"when":              true,
	"where":             true,
	"window":            true,
	"with":              true,
	"alter":             true,
}

// Generated using select typname, typcategory from pg_type
// Map from https://www.postgresql.org/docs/current/catalog-pg-type.html
// Code	Category
// A	Array types
// B	Boolean types
// C	Composite types
// D	Date/time types
// E	Enum types
// G	Geometric types
// I	Network address types
// N	Numeric types
// P	Pseudo-types
// R	Range types
// S	String types
// T	Timespan types
// U	User-defined types
// V	Bit-string types
// X	unknown type
// Z	Internal-use types
var SQLTypeMapping = map[string]string{
	"bool":                                   "Boolean types",
	"bytea":                                  "User-defined types",
	"char":                                   "Internal-use types",
	"name":                                   "String types",
	"int8":                                   "Numeric types",
	"int2":                                   "Numeric types",
	"int2vector":                             "Array types",
	"int4":                                   "Numeric types",
	"regproc":                                "Numeric types",
	"text":                                   "String types",
	"oid":                                    "Numeric types",
	"tid":                                    "User-defined types",
	"xid":                                    "User-defined types",
	"cid":                                    "User-defined types",
	"oidvector":                              "Array types",
	"pg_type":                                "Composite types",
	"pg_attribute":                           "Composite types",
	"pg_proc":                                "Composite types",
	"pg_class":                               "Composite types",
	"json":                                   "User-defined types",
	"xml":                                    "User-defined types",
	"pg_node_tree":                           "Internal-use types",
	"pg_ndistinct":                           "Internal-use types",
	"pg_dependencies":                        "Internal-use types",
	"pg_mcv_list":                            "Internal-use types",
	"pg_ddl_command":                         "Pseudo-types",
	"xid8":                                   "User-defined types",
	"point":                                  "Geometric types",
	"lseg":                                   "Geometric types",
	"path":                                   "Geometric types",
	"box":                                    "Geometric types",
	"polygon":                                "Geometric types",
	"line":                                   "Geometric types",
	"float4":                                 "Numeric types",
	"float8":                                 "Numeric types",
	"unknown":                                "unknown type",
	"circle":                                 "Geometric types",
	"money":                                  "Numeric types",
	"macaddr":                                "User-defined types",
	"inet":                                   "Network address types",
	"cidr":                                   "Network address types",
	"macaddr8":                               "User-defined types",
	"aclitem":                                "User-defined types",
	"bpchar":                                 "String types",
	"varchar":                                "String types",
	"date":                                   "Date/time types",
	"time":                                   "Date/time types",
	"timestamp":                              "Date/time types",
	"timestamptz":                            "Date/time types",
	"interval":                               "Timespan types",
	"timetz":                                 "Date/time types",
	"bit":                                    "Bit-string types",
	"varbit":                                 "Bit-string types",
	"numeric":                                "Numeric types",
	"refcursor":                              "User-defined types",
	"regprocedure":                           "Numeric types",
	"regoper":                                "Numeric types",
	"regoperator":                            "Numeric types",
	"regclass":                               "Numeric types",
	"regcollation":                           "Numeric types",
	"regtype":                                "Numeric types",
	"regrole":                                "Numeric types",
	"regnamespace":                           "Numeric types",
	"uuid":                                   "User-defined types",
	"pg_lsn":                                 "User-defined types",
	"tsvector":                               "User-defined types",
	"gtsvector":                              "User-defined types",
	"tsquery":                                "User-defined types",
	"regconfig":                              "Numeric types",
	"regdictionary":                          "Numeric types",
	"jsonb":                                  "User-defined types",
	"jsonpath":                               "User-defined types",
	"txid_snapshot":                          "User-defined types",
	"pg_snapshot":                            "User-defined types",
	"int4range":                              "Range types",
	"numrange":                               "Range types",
	"tsrange":                                "Range types",
	"tstzrange":                              "Range types",
	"daterange":                              "Range types",
	"int8range":                              "Range types",
	"int4multirange":                         "Range types",
	"nummultirange":                          "Range types",
	"tsmultirange":                           "Range types",
	"tstzmultirange":                         "Range types",
	"datemultirange":                         "Range types",
	"int8multirange":                         "Range types",
	"record":                                 "Pseudo-types",
	"_record":                                "Pseudo-types",
	"cstring":                                "Pseudo-types",
	"any":                                    "Pseudo-types",
	"anyarray":                               "Pseudo-types",
	"void":                                   "Pseudo-types",
	"trigger":                                "Pseudo-types",
	"event_trigger":                          "Pseudo-types",
	"language_handler":                       "Pseudo-types",
	"internal":                               "Pseudo-types",
	"anyelement":                             "Pseudo-types",
	"anynonarray":                            "Pseudo-types",
	"anyenum":                                "Pseudo-types",
	"fdw_handler":                            "Pseudo-types",
	"index_am_handler":                       "Pseudo-types",
	"tsm_handler":                            "Pseudo-types",
	"table_am_handler":                       "Pseudo-types",
	"anyrange":                               "Pseudo-types",
	"anycompatible":                          "Pseudo-types",
	"anycompatiblearray":                     "Pseudo-types",
	"anycompatiblenonarray":                  "Pseudo-types",
	"anycompatiblerange":                     "Pseudo-types",
	"anymultirange":                          "Pseudo-types",
	"anycompatiblemultirange":                "Pseudo-types",
	"pg_brin_bloom_summary":                  "Internal-use types",
	"pg_brin_minmax_multi_summary":           "Internal-use types",
	"_bool":                                  "Array types",
	"_bytea":                                 "Array types",
	"_char":                                  "Array types",
	"_name":                                  "Array types",
	"_int8":                                  "Array types",
	"_int2":                                  "Array types",
	"_int2vector":                            "Array types",
	"_int4":                                  "Array types",
	"_regproc":                               "Array types",
	"_text":                                  "Array types",
	"_oid":                                   "Array types",
	"_tid":                                   "Array types",
	"_xid":                                   "Array types",
	"_cid":                                   "Array types",
	"_oidvector":                             "Array types",
	"_pg_type":                               "Array types",
	"_pg_attribute":                          "Array types",
	"_pg_proc":                               "Array types",
	"_pg_class":                              "Array types",
	"_json":                                  "Array types",
	"_xml":                                   "Array types",
	"_xid8":                                  "Array types",
	"_point":                                 "Array types",
	"_lseg":                                  "Array types",
	"_path":                                  "Array types",
	"_box":                                   "Array types",
	"_polygon":                               "Array types",
	"_line":                                  "Array types",
	"_float4":                                "Array types",
	"_float8":                                "Array types",
	"_circle":                                "Array types",
	"_money":                                 "Array types",
	"_macaddr":                               "Array types",
	"_inet":                                  "Array types",
	"_cidr":                                  "Array types",
	"_macaddr8":                              "Array types",
	"_aclitem":                               "Array types",
	"_bpchar":                                "Array types",
	"_varchar":                               "Array types",
	"_date":                                  "Array types",
	"_time":                                  "Array types",
	"_timestamp":                             "Array types",
	"_timestamptz":                           "Array types",
	"_interval":                              "Array types",
	"_timetz":                                "Array types",
	"_bit":                                   "Array types",
	"_varbit":                                "Array types",
	"_numeric":                               "Array types",
	"_refcursor":                             "Array types",
	"_regprocedure":                          "Array types",
	"_regoper":                               "Array types",
	"_regoperator":                           "Array types",
	"_regclass":                              "Array types",
	"_regcollation":                          "Array types",
	"_regtype":                               "Array types",
	"_regrole":                               "Array types",
	"_regnamespace":                          "Array types",
	"_uuid":                                  "Array types",
	"_pg_lsn":                                "Array types",
	"_tsvector":                              "Array types",
	"_gtsvector":                             "Array types",
	"_tsquery":                               "Array types",
	"_regconfig":                             "Array types",
	"_regdictionary":                         "Array types",
	"_jsonb":                                 "Array types",
	"_jsonpath":                              "Array types",
	"_txid_snapshot":                         "Array types",
	"_pg_snapshot":                           "Array types",
	"_int4range":                             "Array types",
	"_numrange":                              "Array types",
	"_tsrange":                               "Array types",
	"_tstzrange":                             "Array types",
	"_daterange":                             "Array types",
	"_int8range":                             "Array types",
	"_int4multirange":                        "Array types",
	"_nummultirange":                         "Array types",
	"_tsmultirange":                          "Array types",
	"_tstzmultirange":                        "Array types",
	"_datemultirange":                        "Array types",
	"_int8multirange":                        "Array types",
	"_cstring":                               "Array types",
	"pg_attrdef":                             "Composite types",
	"_pg_attrdef":                            "Array types",
	"pg_constraint":                          "Composite types",
	"_pg_constraint":                         "Array types",
	"pg_inherits":                            "Composite types",
	"_pg_inherits":                           "Array types",
	"pg_index":                               "Composite types",
	"_pg_index":                              "Array types",
	"pg_operator":                            "Composite types",
	"_pg_operator":                           "Array types",
	"pg_opfamily":                            "Composite types",
	"_pg_opfamily":                           "Array types",
	"pg_opclass":                             "Composite types",
	"_pg_opclass":                            "Array types",
	"pg_am":                                  "Composite types",
	"_pg_am":                                 "Array types",
	"pg_amop":                                "Composite types",
	"_pg_amop":                               "Array types",
	"pg_amproc":                              "Composite types",
	"_pg_amproc":                             "Array types",
	"pg_language":                            "Composite types",
	"_pg_language":                           "Array types",
	"pg_largeobject_metadata":                "Composite types",
	"_pg_largeobject_metadata":               "Array types",
	"pg_largeobject":                         "Composite types",
	"_pg_largeobject":                        "Array types",
	"pg_aggregate":                           "Composite types",
	"_pg_aggregate":                          "Array types",
	"pg_statistic":                           "Composite types",
	"_pg_statistic":                          "Array types",
	"pg_statistic_ext":                       "Composite types",
	"_pg_statistic_ext":                      "Array types",
	"pg_statistic_ext_data":                  "Composite types",
	"_pg_statistic_ext_data":                 "Array types",
	"pg_rewrite":                             "Composite types",
	"_pg_rewrite":                            "Array types",
	"pg_trigger":                             "Composite types",
	"_pg_trigger":                            "Array types",
	"pg_event_trigger":                       "Composite types",
	"_pg_event_trigger":                      "Array types",
	"pg_description":                         "Composite types",
	"_pg_description":                        "Array types",
	"pg_cast":                                "Composite types",
	"_pg_cast":                               "Array types",
	"pg_enum":                                "Composite types",
	"_pg_enum":                               "Array types",
	"pg_namespace":                           "Composite types",
	"_pg_namespace":                          "Array types",
	"pg_conversion":                          "Composite types",
	"_pg_conversion":                         "Array types",
	"pg_depend":                              "Composite types",
	"_pg_depend":                             "Array types",
	"pg_database":                            "Composite types",
	"_pg_database":                           "Array types",
	"pg_db_role_setting":                     "Composite types",
	"_pg_db_role_setting":                    "Array types",
	"pg_tablespace":                          "Composite types",
	"_pg_tablespace":                         "Array types",
	"pg_authid":                              "Composite types",
	"_pg_authid":                             "Array types",
	"pg_auth_members":                        "Composite types",
	"_pg_auth_members":                       "Array types",
	"pg_shdepend":                            "Composite types",
	"_pg_shdepend":                           "Array types",
	"pg_shdescription":                       "Composite types",
	"_pg_shdescription":                      "Array types",
	"pg_ts_config":                           "Composite types",
	"_pg_ts_config":                          "Array types",
	"pg_ts_config_map":                       "Composite types",
	"_pg_ts_config_map":                      "Array types",
	"pg_ts_dict":                             "Composite types",
	"_pg_ts_dict":                            "Array types",
	"pg_ts_parser":                           "Composite types",
	"_pg_ts_parser":                          "Array types",
	"pg_ts_template":                         "Composite types",
	"_pg_ts_template":                        "Array types",
	"pg_extension":                           "Composite types",
	"_pg_extension":                          "Array types",
	"pg_foreign_data_wrapper":                "Composite types",
	"_pg_foreign_data_wrapper":               "Array types",
	"pg_foreign_server":                      "Composite types",
	"_pg_foreign_server":                     "Array types",
	"pg_user_mapping":                        "Composite types",
	"_pg_user_mapping":                       "Array types",
	"pg_foreign_table":                       "Composite types",
	"_pg_foreign_table":                      "Array types",
	"pg_policy":                              "Composite types",
	"_pg_policy":                             "Array types",
	"pg_replication_origin":                  "Composite types",
	"_pg_replication_origin":                 "Array types",
	"pg_default_acl":                         "Composite types",
	"_pg_default_acl":                        "Array types",
	"pg_init_privs":                          "Composite types",
	"_pg_init_privs":                         "Array types",
	"pg_seclabel":                            "Composite types",
	"_pg_seclabel":                           "Array types",
	"pg_shseclabel":                          "Composite types",
	"_pg_shseclabel":                         "Array types",
	"pg_collation":                           "Composite types",
	"_pg_collation":                          "Array types",
	"pg_parameter_acl":                       "Composite types",
	"_pg_parameter_acl":                      "Array types",
	"pg_partitioned_table":                   "Composite types",
	"_pg_partitioned_table":                  "Array types",
	"pg_range":                               "Composite types",
	"_pg_range":                              "Array types",
	"pg_transform":                           "Composite types",
	"_pg_transform":                          "Array types",
	"pg_sequence":                            "Composite types",
	"_pg_sequence":                           "Array types",
	"pg_publication":                         "Composite types",
	"_pg_publication":                        "Array types",
	"pg_publication_namespace":               "Composite types",
	"_pg_publication_namespace":              "Array types",
	"pg_publication_rel":                     "Composite types",
	"_pg_publication_rel":                    "Array types",
	"pg_subscription":                        "Composite types",
	"_pg_subscription":                       "Array types",
	"pg_subscription_rel":                    "Composite types",
	"_pg_subscription_rel":                   "Array types",
	"pg_roles":                               "Composite types",
	"_pg_roles":                              "Array types",
	"pg_shadow":                              "Composite types",
	"_pg_shadow":                             "Array types",
	"pg_group":                               "Composite types",
	"_pg_group":                              "Array types",
	"pg_user":                                "Composite types",
	"_pg_user":                               "Array types",
	"pg_policies":                            "Composite types",
	"_pg_policies":                           "Array types",
	"pg_rules":                               "Composite types",
	"_pg_rules":                              "Array types",
	"pg_views":                               "Composite types",
	"_pg_views":                              "Array types",
	"pg_tables":                              "Composite types",
	"_pg_tables":                             "Array types",
	"pg_matviews":                            "Composite types",
	"_pg_matviews":                           "Array types",
	"pg_indexes":                             "Composite types",
	"_pg_indexes":                            "Array types",
	"pg_sequences":                           "Composite types",
	"_pg_sequences":                          "Array types",
	"pg_stats":                               "Composite types",
	"_pg_stats":                              "Array types",
	"pg_stats_ext":                           "Composite types",
	"_pg_stats_ext":                          "Array types",
	"pg_stats_ext_exprs":                     "Composite types",
	"_pg_stats_ext_exprs":                    "Array types",
	"pg_publication_tables":                  "Composite types",
	"_pg_publication_tables":                 "Array types",
	"pg_locks":                               "Composite types",
	"_pg_locks":                              "Array types",
	"pg_cursors":                             "Composite types",
	"_pg_cursors":                            "Array types",
	"pg_available_extensions":                "Composite types",
	"_pg_available_extensions":               "Array types",
	"pg_available_extension_versions":        "Composite types",
	"_pg_available_extension_versions":       "Array types",
	"pg_prepared_xacts":                      "Composite types",
	"_pg_prepared_xacts":                     "Array types",
	"pg_prepared_statements":                 "Composite types",
	"_pg_prepared_statements":                "Array types",
	"pg_seclabels":                           "Composite types",
	"_pg_seclabels":                          "Array types",
	"pg_settings":                            "Composite types",
	"_pg_settings":                           "Array types",
	"pg_file_settings":                       "Composite types",
	"_pg_file_settings":                      "Array types",
	"pg_hba_file_rules":                      "Composite types",
	"_pg_hba_file_rules":                     "Array types",
	"pg_ident_file_mappings":                 "Composite types",
	"_pg_ident_file_mappings":                "Array types",
	"pg_timezone_abbrevs":                    "Composite types",
	"_pg_timezone_abbrevs":                   "Array types",
	"pg_timezone_names":                      "Composite types",
	"_pg_timezone_names":                     "Array types",
	"pg_config":                              "Composite types",
	"_pg_config":                             "Array types",
	"pg_shmem_allocations":                   "Composite types",
	"_pg_shmem_allocations":                  "Array types",
	"pg_backend_memory_contexts":             "Composite types",
	"_pg_backend_memory_contexts":            "Array types",
	"pg_stat_all_tables":                     "Composite types",
	"_pg_stat_all_tables":                    "Array types",
	"pg_stat_xact_all_tables":                "Composite types",
	"_pg_stat_xact_all_tables":               "Array types",
	"pg_stat_sys_tables":                     "Composite types",
	"_pg_stat_sys_tables":                    "Array types",
	"pg_stat_xact_sys_tables":                "Composite types",
	"_pg_stat_xact_sys_tables":               "Array types",
	"pg_stat_user_tables":                    "Composite types",
	"_pg_stat_user_tables":                   "Array types",
	"pg_stat_xact_user_tables":               "Composite types",
	"_pg_stat_xact_user_tables":              "Array types",
	"pg_statio_all_tables":                   "Composite types",
	"_pg_statio_all_tables":                  "Array types",
	"pg_statio_sys_tables":                   "Composite types",
	"_pg_statio_sys_tables":                  "Array types",
	"pg_statio_user_tables":                  "Composite types",
	"_pg_statio_user_tables":                 "Array types",
	"pg_stat_all_indexes":                    "Composite types",
	"_pg_stat_all_indexes":                   "Array types",
	"pg_stat_sys_indexes":                    "Composite types",
	"_pg_stat_sys_indexes":                   "Array types",
	"pg_stat_user_indexes":                   "Composite types",
	"_pg_stat_user_indexes":                  "Array types",
	"pg_statio_all_indexes":                  "Composite types",
	"_pg_statio_all_indexes":                 "Array types",
	"pg_statio_sys_indexes":                  "Composite types",
	"_pg_statio_sys_indexes":                 "Array types",
	"pg_statio_user_indexes":                 "Composite types",
	"_pg_statio_user_indexes":                "Array types",
	"pg_statio_all_sequences":                "Composite types",
	"_pg_statio_all_sequences":               "Array types",
	"pg_statio_sys_sequences":                "Composite types",
	"_pg_statio_sys_sequences":               "Array types",
	"pg_statio_user_sequences":               "Composite types",
	"_pg_statio_user_sequences":              "Array types",
	"pg_stat_activity":                       "Composite types",
	"_pg_stat_activity":                      "Array types",
	"pg_stat_replication":                    "Composite types",
	"_pg_stat_replication":                   "Array types",
	"pg_stat_slru":                           "Composite types",
	"_pg_stat_slru":                          "Array types",
	"pg_stat_wal_receiver":                   "Composite types",
	"_pg_stat_wal_receiver":                  "Array types",
	"pg_stat_recovery_prefetch":              "Composite types",
	"_pg_stat_recovery_prefetch":             "Array types",
	"pg_stat_subscription":                   "Composite types",
	"_pg_stat_subscription":                  "Array types",
	"pg_stat_ssl":                            "Composite types",
	"_pg_stat_ssl":                           "Array types",
	"pg_stat_gssapi":                         "Composite types",
	"_pg_stat_gssapi":                        "Array types",
	"pg_replication_slots":                   "Composite types",
	"_pg_replication_slots":                  "Array types",
	"pg_stat_replication_slots":              "Composite types",
	"_pg_stat_replication_slots":             "Array types",
	"pg_stat_database":                       "Composite types",
	"_pg_stat_database":                      "Array types",
	"pg_stat_database_conflicts":             "Composite types",
	"_pg_stat_database_conflicts":            "Array types",
	"pg_stat_user_functions":                 "Composite types",
	"_pg_stat_user_functions":                "Array types",
	"pg_stat_xact_user_functions":            "Composite types",
	"_pg_stat_xact_user_functions":           "Array types",
	"pg_stat_archiver":                       "Composite types",
	"_pg_stat_archiver":                      "Array types",
	"pg_stat_bgwriter":                       "Composite types",
	"_pg_stat_bgwriter":                      "Array types",
	"pg_stat_wal":                            "Composite types",
	"_pg_stat_wal":                           "Array types",
	"pg_stat_progress_analyze":               "Composite types",
	"_pg_stat_progress_analyze":              "Array types",
	"pg_stat_progress_vacuum":                "Composite types",
	"_pg_stat_progress_vacuum":               "Array types",
	"pg_stat_progress_cluster":               "Composite types",
	"_pg_stat_progress_cluster":              "Array types",
	"pg_stat_progress_create_index":          "Composite types",
	"_pg_stat_progress_create_index":         "Array types",
	"pg_stat_progress_basebackup":            "Composite types",
	"_pg_stat_progress_basebackup":           "Array types",
	"pg_stat_progress_copy":                  "Composite types",
	"_pg_stat_progress_copy":                 "Array types",
	"pg_user_mappings":                       "Composite types",
	"_pg_user_mappings":                      "Array types",
	"pg_replication_origin_status":           "Composite types",
	"_pg_replication_origin_status":          "Array types",
	"pg_stat_subscription_stats":             "Composite types",
	"_pg_stat_subscription_stats":            "Array types",
	"cardinal_number":                        "Numeric types",
	"_cardinal_number":                       "Array types",
	"character_data":                         "String types",
	"_character_data":                        "Array types",
	"sql_identifier":                         "String types",
	"_sql_identifier":                        "Array types",
	"information_schema_catalog_name":        "Composite types",
	"_information_schema_catalog_name":       "Array types",
	"time_stamp":                             "Date/time types",
	"_time_stamp":                            "Array types",
	"yes_or_no":                              "String types",
	"_yes_or_no":                             "Array types",
	"applicable_roles":                       "Composite types",
	"_applicable_roles":                      "Array types",
	"administrable_role_authorizations":      "Composite types",
	"_administrable_role_authorizations":     "Array types",
	"attributes":                             "Composite types",
	"_attributes":                            "Array types",
	"character_sets":                         "Composite types",
	"_character_sets":                        "Array types",
	"check_constraint_routine_usage":         "Composite types",
	"_check_constraint_routine_usage":        "Array types",
	"check_constraints":                      "Composite types",
	"_check_constraints":                     "Array types",
	"collations":                             "Composite types",
	"_collations":                            "Array types",
	"collation_character_set_applicability":  "Composite types",
	"_collation_character_set_applicability": "Array types",
	"column_column_usage":                    "Composite types",
	"_column_column_usage":                   "Array types",
	"column_domain_usage":                    "Composite types",
	"_column_domain_usage":                   "Array types",
	"column_privileges":                      "Composite types",
	"_column_privileges":                     "Array types",
	"column_udt_usage":                       "Composite types",
	"_column_udt_usage":                      "Array types",
	"columns":                                "Composite types",
	"_columns":                               "Array types",
	"constraint_column_usage":                "Composite types",
	"_constraint_column_usage":               "Array types",
	"constraint_table_usage":                 "Composite types",
	"_constraint_table_usage":                "Array types",
	"domain_constraints":                     "Composite types",
	"_domain_constraints":                    "Array types",
	"domain_udt_usage":                       "Composite types",
	"_domain_udt_usage":                      "Array types",
	"domains":                                "Composite types",
	"_domains":                               "Array types",
	"enabled_roles":                          "Composite types",
	"_enabled_roles":                         "Array types",
	"key_column_usage":                       "Composite types",
	"_key_column_usage":                      "Array types",
	"parameters":                             "Composite types",
	"_parameters":                            "Array types",
	"referential_constraints":                "Composite types",
	"_referential_constraints":               "Array types",
	"role_column_grants":                     "Composite types",
	"_role_column_grants":                    "Array types",
	"routine_column_usage":                   "Composite types",
	"_routine_column_usage":                  "Array types",
	"routine_privileges":                     "Composite types",
	"_routine_privileges":                    "Array types",
	"role_routine_grants":                    "Composite types",
	"_role_routine_grants":                   "Array types",
	"routine_routine_usage":                  "Composite types",
	"_routine_routine_usage":                 "Array types",
	"routine_sequence_usage":                 "Composite types",
	"_routine_sequence_usage":                "Array types",
	"routine_table_usage":                    "Composite types",
	"_routine_table_usage":                   "Array types",
	"routines":                               "Composite types",
	"_routines":                              "Array types",
	"schemata":                               "Composite types",
	"_schemata":                              "Array types",
	"sequences":                              "Composite types",
	"_sequences":                             "Array types",
	"sql_features":                           "Composite types",
	"_sql_features":                          "Array types",
	"sql_implementation_info":                "Composite types",
	"_sql_implementation_info":               "Array types",
	"sql_parts":                              "Composite types",
	"_sql_parts":                             "Array types",
	"sql_sizing":                             "Composite types",
	"_sql_sizing":                            "Array types",
	"table_constraints":                      "Composite types",
	"_table_constraints":                     "Array types",
	"table_privileges":                       "Composite types",
	"_table_privileges":                      "Array types",
	"role_table_grants":                      "Composite types",
	"_role_table_grants":                     "Array types",
	"tables":                                 "Composite types",
	"_tables":                                "Array types",
	"transforms":                             "Composite types",
	"_transforms":                            "Array types",
	"triggered_update_columns":               "Composite types",
	"_triggered_update_columns":              "Array types",
	"triggers":                               "Composite types",
	"_triggers":                              "Array types",
	"udt_privileges":                         "Composite types",
	"_udt_privileges":                        "Array types",
	"role_udt_grants":                        "Composite types",
	"_role_udt_grants":                       "Array types",
	"usage_privileges":                       "Composite types",
	"_usage_privileges":                      "Array types",
	"role_usage_grants":                      "Composite types",
	"_role_usage_grants":                     "Array types",
	"user_defined_types":                     "Composite types",
	"_user_defined_types":                    "Array types",
	"view_column_usage":                      "Composite types",
	"_view_column_usage":                     "Array types",
	"view_routine_usage":                     "Composite types",
	"_view_routine_usage":                    "Array types",
	"view_table_usage":                       "Composite types",
	"_view_table_usage":                      "Array types",
	"views":                                  "Composite types",
	"_views":                                 "Array types",
	"data_type_privileges":                   "Composite types",
	"_data_type_privileges":                  "Array types",
	"element_types":                          "Composite types",
	"_element_types":                         "Array types",
	"_pg_foreign_table_columns":              "Composite types",
	"__pg_foreign_table_columns":             "Array types",
	"column_options":                         "Composite types",
	"_column_options":                        "Array types",
	"_pg_foreign_data_wrappers":              "Composite types",
	"__pg_foreign_data_wrappers":             "Array types",
	"foreign_data_wrapper_options":           "Composite types",
	"_foreign_data_wrapper_options":          "Array types",
	"foreign_data_wrappers":                  "Composite types",
	"_foreign_data_wrappers":                 "Array types",
	"_pg_foreign_servers":                    "Composite types",
	"__pg_foreign_servers":                   "Array types",
	"foreign_server_options":                 "Composite types",
	"_foreign_server_options":                "Array types",
	"foreign_servers":                        "Composite types",
	"_foreign_servers":                       "Array types",
	"_pg_foreign_tables":                     "Composite types",
	"__pg_foreign_tables":                    "Array types",
	"foreign_table_options":                  "Composite types",
	"_foreign_table_options":                 "Array types",
	"foreign_tables":                         "Composite types",
	"_foreign_tables":                        "Array types",
	"__pg_user_mappings":                     "Array types",
	"user_mapping_options":                   "Composite types",
	"_user_mapping_options":                  "Array types",
	"user_mappings":                          "Composite types",
	"_user_mappings":                         "Array types",
	"data_src":                               "Composite types",
	"_data_src":                              "Array types",
	"datsrcln":                               "Composite types",
	"_datsrcln":                              "Array types",
	"deriv_cd":                               "Composite types",
	"_deriv_cd":                              "Array types",
	"fd_group":                               "Composite types",
	"_fd_group":                              "Array types",
	"food_des":                               "Composite types",
	"_food_des":                              "Array types",
	"footnote":                               "Composite types",
	"_footnote":                              "Array types",
	"nut_data":                               "Composite types",
	"_nut_data":                              "Array types",
	"nutr_def":                               "Composite types",
	"_nutr_def":                              "Array types",
	"src_cd":                                 "Composite types",
	"_src_cd":                                "Array types",
	"weight":                                 "Composite types",
	"_weight":                                "Array types",
}
